#!/bin/sh
## Dmenu based frontend to read RSS directory

RSS=$XDG_DATA_HOME/rss

# File for unread count, adjust to suit your setup
UNREADCOUNT="$XDG_RUNTIME_DIR"/statusbar/rss
trap 'update_count' EXIT

# List all feeds
list_all() {
	cd "$RSS" && ls
	printf '%s\n%s\n' "Back" "Exit"
}	

# List all feeds. Some titles can be expressed as a directory (since `/` is not a valid character in filenames, we allow `$RSS/read/myfeed/something neat for my title with a / in it`.)
list_sub() {
	find "$RSS/$@" -type f | sed 's|^.*read/||'
	printf '%s\n%s\n%s\n' "Back" "Clear Unread" "Exit"
}

# Helper function to do a nested search on sh
list_new() {
	ls "$RSS" | while read -r dir; do
		for i in "$dir"/unread/*; do
			test -f "$i" && dirname "$i"
		done
	done
}

# List all feeds with unread content
list_main() {
	list_new | sed 's|/unread||' | sort -u
	printf '%s\n%s\n' "View All" "Exit"
}

# This, you can simply change to a single printf
# If you prefer an unread count of 0 in your file
# `list_new | wc -l > "$UNREADCOUNT"`
update_count() {
	unread="$(list_new | wc -l)"
	case "$unread" in
		0)	echo -n > "$UNREADCOUNT" 						;;
		*)  printf '%s unread\n' "$unread" > "$UNREADCOUNT" ;; 
	esac
}

# Move from unread to read
scrub() {
	# unread to read
	new="$(printf '%s\n' "$@" | sed 's/unread/read/')"
	# Ensure we have a `read` directory
	mkdir -p "$(dirname "$new")"
	case "$@" in
		*unread*) mv "$@" "$new" ;;
	esac
}

plumb() {
	plumber < "$RSS/$@" >/dev/null &
	scrub "$RSS/$@"
}

# Read all selections and plumb any good result
handle() {
	# Build command to call rss
	case $@ in
		# Remove all entries in unread
		Clear*)		for i in "$RSS/$@"/unread/*; do
						scrub "$i"
					done 
					exec $0 main ;;
		View*)		exec $0 all  ;;
		*unread*) 	plumb "$@" ;;
		*read*)		plumb "$@" ;;
		Back)		exec $0 main ;;
		Exit) 		exit 0 		 ;;
		*)			exec $0 "$@" ;;
	esac
}

# If we have no arguments, run our main list
test -z "$1" && set -- main

# Set pipeline to run based on command-line arguments
case "$@" in
	main)	run() { list_main     | dmenu -p "Select feed: "; } ;;
	all)	run() { list_all      | dmenu -p "Select feed: "; } ;; 
	*)		run() { list_sub "$@" | dmenu -p "Select post: "; } ;;
esac

# Ugly inline-while loop, but hey.
run "$@" | while read -r input; do { handle "$input"; }; done
