#!/bin/sh
## Script to fetch RSS + atom feeds 

RSS="$XDG_DATA_HOME"/rss
XSLT="/usr/local/share/rss.xslt"

build() {
	read -r feed
	# Some titles need cleaning
	feed="$(printf '%s\n' "$feed" | sed 's|^.*://||' | sed 's|/.*||')"
	while read -r link title; do
		if ! ls "$RSS/$feed/"*read"/$title" >/dev/null 2>&1; then
			mkdir -p "$(dirname "$RSS/$feed/unread/$title")"
			echo "$link" > "$RSS/$feed/unread/$title"
		fi
	done
}

fetch() {
	curl -sSfL "$1" | xsltproc "$XSLT" - | build
}

while read -r url; do
	fetch "$url"
done < "$XDG_DATA_HOME"/feedurls
wait
# you can comment this out, it's just for my status bar
if ls -d "$RSS"/*/unread/* >/dev/null 2>&1; then 
	dirname "$RSS"/*/unread/* | wc -l > "$XDG_RUNTIME_DIR/statusbar/rss"
fi

